% test function

clear; close all;
Im = {'imData/1.png' 'imData/2.png' 'imData/3.png' 'imData/4.png' ...
    'imData/5.png' 'imData/6.png' 'imData/7.png' 'imData/8.png' ...
    'imData/9.png' 'imData/10.png' 'imData/11.png' 'imData/12.png' ...
    'imData/13.png' 'imData/14.png' 'imData/15.png' 'imData/16.png' ...
    'imData/17.png' 'imData/18.png' 'imData/19.png' 'imData/20.png' };
blk_size = 28;
method = 'm+lpq';
for jj = 1:length(Im)
        main(Im{jj},blk_size,method)
end